### ISSUE TITLE
Issue with wozmon.sh

### ISSUE THREAD

**Issue by Tt396** [IanSeyler/wozmon_x86-64#1]
After running "./wozmon.sh setup" I get the error "mv: cannot stat 'os/Pure64/bin/pure64.sys': No such file or directory"

**Comment by IanSeyler** [comment]
Thanks for reporting this. I'll get it fixed.

**Comment by IanSeyler** [comment]
Pure64 recently switched to separate binaries for BIOS & UEFI booting. I've updated the script to pull the BIOS binary. Looks like there is another issue with it not functioning properly. Looking into the issue.

**Comment by IanSeyler** [comment]
Please try this again. I've updated wozmon.asm to respect the correct flag for [b_input] and I've also fixed an issue with the latest Pure64.
